In [1]:
import pandas as pd
import uuid
import random

## Create Dummy DataFrame

In [2]:
user_uuid = [str(uuid.uuid1()) for i in range(0,10_000)]

event_ids = [str(uuid.uuid1()) for i in range(0,1_000_000)]

category_ids = [round(random.random()*45) for i in range(0,1_000_000)]

user_ls = [user_uuid[round(random.random()*len(user_uuid))-1] for i in range(0,1_000_000)]

value_1 = [random.random() for i in range(0,1_000_000)]

value_2 = [random.random()*25 for i in range(0,1_000_000)]

value_3 = [random.random()*300 for i in range(0,1_000_000)]

df = pd.DataFrame({'user':user_ls,'event':event_ids,'category':category_ids,'a':value_1,'b':value_2,'c':value_3})

df

,user,event,category,a,b,c
0,08195568-736e-11ed-a2b2-52b6cb0f4fb4,08199a32-736e-11ed-a2b2-52b6cb0f4fb4,44,0.610372,12.292282,24.335547
1,081797d2-736e-11ed-a2b2-52b6cb0f4fb4,08199a78-736e-11ed-a2b2-52b6cb0f4fb4,35,0.078606,7.961856,296.394964
2,081734cc-736e-11ed-a2b2-52b6cb0f4fb4,08199aa0-736e-11ed-a2b2-52b6cb0f4fb4,26,0.384753,1.983894,258.235820
3,08168d9c-736e-11ed-a2b2-52b6cb0f4fb4,08199ac8-736e-11ed-a2b2-52b6cb0f4fb4,24,0.310100,1.622137,158.499581
4,0812d83c-736e-11ed-a2b2-52b6cb0f4fb4,08199af0-736e-11ed-a2b2-52b6cb0f4fb4,39,0.279737,7.987843,243.485304
...,...,...,...,...,...,...
999995,0815a184-736e-11ed-a2b2-52b6cb0f4fb4,092aed04-736e-11ed-a2b2-52b6cb0f4fb4,17,0.223698,4.090536,276.347277
999996,081775a4-736e-11ed-a2b2-52b6cb0f4fb4,092aed18-736e-11ed-a2b2-52b6cb0f4fb4,3,0.139040,17.237403,104.239157
999997,081791ec-736e-11ed-a2b2-52b6cb0f4fb4,092aed2c-736e-11ed-a2b2-52b6cb0f4fb4,17,0.869186,22.899896,235.937092
999998,0812c46e-736e-11ed-a2b2-52b6cb0f4fb4,092aed36-736e-11ed-a2b2-52b6cb0f4fb4,37,0.634560,15.790505,111.128829
999999,0815ef2c-736e-11ed-a2b2-52b6cb0f4fb4,092aed4a-736e-11ed-a2b2-52b6cb0f4fb4,36,0.164187,12.940862,119.524636

In [3]:
from panda_searches import PandaSearches

## Indexing

In [4]:
df.ps.indexing('user','event','category')

Indexing user

  0%|          | 0/1000000 [00:00<?, ?it/s]

============
Indexing event

  0%|          | 0/1000000 [00:00<?, ?it/s]

============
Indexing category

  0%|          | 0/1000000 [00:00<?, ?it/s]

============

## Search Comparison

In [5]:
test_user = df.user.sample(1).iloc[0] # Getting test user
test_user

'0818e466-736e-11ed-a2b2-52b6cb0f4fb4'

In [6]:
%%time

df[df['user']==test_user]

CPU times: user 68.6 ms, sys: 2.56 ms, total: 71.2 ms
Wall time: 71.5 ms

,user,event,category,a,b,c
16750,0818e466-736e-11ed-a2b2-52b6cb0f4fb4,0820193e-736e-11ed-a2b2-52b6cb0f4fb4,6,0.954642,19.934592,43.666873
25227,0818e466-736e-11ed-a2b2-52b6cb0f4fb4,08226f40-736e-11ed-a2b2-52b6cb0f4fb4,28,0.295177,16.363659,98.606231
25514,0818e466-736e-11ed-a2b2-52b6cb0f4fb4,0822834a-736e-11ed-a2b2-52b6cb0f4fb4,40,0.629807,24.535946,129.954073
29598,0818e466-736e-11ed-a2b2-52b6cb0f4fb4,08239fc8-736e-11ed-a2b2-52b6cb0f4fb4,3,0.667486,20.934258,164.630081
40894,0818e466-736e-11ed-a2b2-52b6cb0f4fb4,0826b118-736e-11ed-a2b2-52b6cb0f4fb4,17,0.599447,13.780017,252.706999
...,...,...,...,...,...,...
939503,0818e466-736e-11ed-a2b2-52b6cb0f4fb4,091a86ee-736e-11ed-a2b2-52b6cb0f4fb4,24,0.649750,14.717183,40.484382
943143,0818e466-736e-11ed-a2b2-52b6cb0f4fb4,091b8422-736e-11ed-a2b2-52b6cb0f4fb4,38,0.270739,19.269465,15.551091
954308,0818e466-736e-11ed-a2b2-52b6cb0f4fb4,091e8a32-736e-11ed-a2b2-52b6cb0f4fb4,23,0.013681,17.321016,124.860648
963916,0818e466-736e-11ed-a2b2-52b6cb0f4fb4,09212472-736e-11ed-a2b2-52b6cb0f4fb4,20,0.705655,0.514945,38.379271
995350,0818e466-736e-11ed-a2b2-52b6cb0f4fb4,0929aafc-736e-11ed-a2b2-52b6cb0f4fb4,32,0.484433,16.337921,285.084624

In [7]:
%%time

df.ps[('user',test_user)]

CPU times: user 817 Âµs, sys: 66 Âµs, total: 883 Âµs
Wall time: 848 Âµs

,user,event,category,a,b,c
516111,0818e466-736e-11ed-a2b2-52b6cb0f4fb4,08a78d4c-736e-11ed-a2b2-52b6cb0f4fb4,29,0.406284,9.745465,128.860642
228881,0818e466-736e-11ed-a2b2-52b6cb0f4fb4,08599fec-736e-11ed-a2b2-52b6cb0f4fb4,37,0.010161,14.686247,186.969485
359955,0818e466-736e-11ed-a2b2-52b6cb0f4fb4,087d2d90-736e-11ed-a2b2-52b6cb0f4fb4,15,0.312178,8.497728,99.284896
995350,0818e466-736e-11ed-a2b2-52b6cb0f4fb4,0929aafc-736e-11ed-a2b2-52b6cb0f4fb4,32,0.484433,16.337921,285.084624
943143,0818e466-736e-11ed-a2b2-52b6cb0f4fb4,091b8422-736e-11ed-a2b2-52b6cb0f4fb4,38,0.270739,19.269465,15.551091
...,...,...,...,...,...,...
566252,0818e466-736e-11ed-a2b2-52b6cb0f4fb4,08b534ec-736e-11ed-a2b2-52b6cb0f4fb4,21,0.242151,19.920212,297.342855
423917,0818e466-736e-11ed-a2b2-52b6cb0f4fb4,088e8e1e-736e-11ed-a2b2-52b6cb0f4fb4,43,0.909698,14.808419,266.708357
939503,0818e466-736e-11ed-a2b2-52b6cb0f4fb4,091a86ee-736e-11ed-a2b2-52b6cb0f4fb4,24,0.649750,14.717183,40.484382
875000,0818e466-736e-11ed-a2b2-52b6cb0f4fb4,090906c6-736e-11ed-a2b2-52b6cb0f4fb4,45,0.445117,19.795932,205.995028
799226,0818e466-736e-11ed-a2b2-52b6cb0f4fb4,08f47b98-736e-11ed-a2b2-52b6cb0f4fb4,44,0.062190,17.752959,156.134580

## Search with AND/OR

In [8]:
%%time

df[(df['user']==test_user) & (df['category']==2)]

CPU times: user 73.8 ms, sys: 1.82 ms, total: 75.6 ms
Wall time: 74.2 ms

,user,event,category,a,b,c
46938,0818e466-736e-11ed-a2b2-52b6cb0f4fb4,08285400-736e-11ed-a2b2-52b6cb0f4fb4,2,0.453257,1.385590,199.469174
289592,0818e466-736e-11ed-a2b2-52b6cb0f4fb4,086a1052-736e-11ed-a2b2-52b6cb0f4fb4,2,0.841562,5.207712,192.198093
567007,0818e466-736e-11ed-a2b2-52b6cb0f4fb4,08b56926-736e-11ed-a2b2-52b6cb0f4fb4,2,0.500005,5.086936,209.715748
605344,0818e466-736e-11ed-a2b2-52b6cb0f4fb4,08bfccb8-736e-11ed-a2b2-52b6cb0f4fb4,2,0.996349,13.175147,16.132618

In [9]:
%%time

df.ps[ [ ('user',test_user),'and',('category',2) ] ]

CPU times: user 6.33 ms, sys: 2.42 ms, total: 8.74 ms
Wall time: 8.65 ms

,user,event,category,a,b,c
605344,0818e466-736e-11ed-a2b2-52b6cb0f4fb4,08bfccb8-736e-11ed-a2b2-52b6cb0f4fb4,2,0.996349,13.175147,16.132618
289592,0818e466-736e-11ed-a2b2-52b6cb0f4fb4,086a1052-736e-11ed-a2b2-52b6cb0f4fb4,2,0.841562,5.207712,192.198093
46938,0818e466-736e-11ed-a2b2-52b6cb0f4fb4,08285400-736e-11ed-a2b2-52b6cb0f4fb4,2,0.453257,1.385590,199.469174
567007,0818e466-736e-11ed-a2b2-52b6cb0f4fb4,08b56926-736e-11ed-a2b2-52b6cb0f4fb4,2,0.500005,5.086936,209.715748

## Complex Search

In [10]:
test_user_list = list(df.user.sample(5))
test_user_list

['08168b4e-736e-11ed-a2b2-52b6cb0f4fb4',
 '081698aa-736e-11ed-a2b2-52b6cb0f4fb4',
 '0818d246-736e-11ed-a2b2-52b6cb0f4fb4',
 '08138002-736e-11ed-a2b2-52b6cb0f4fb4',
 '08122ed2-736e-11ed-a2b2-52b6cb0f4fb4']

In [11]:
%%time

df[(df['user'].isin(test_user_list)) | ((df['user']==test_user) & (df['category']==2))]

CPU times: user 115 ms, sys: 4.28 ms, total: 120 ms
Wall time: 119 ms

,user,event,category,a,b,c
295,08122ed2-736e-11ed-a2b2-52b6cb0f4fb4,0819c39a-736e-11ed-a2b2-52b6cb0f4fb4,22,0.821416,0.829862,168.978616
649,08122ed2-736e-11ed-a2b2-52b6cb0f4fb4,0819f108-736e-11ed-a2b2-52b6cb0f4fb4,1,0.369514,10.379635,0.265233
2187,08122ed2-736e-11ed-a2b2-52b6cb0f4fb4,081ab872-736e-11ed-a2b2-52b6cb0f4fb4,33,0.087270,16.867430,117.989447
2325,08138002-736e-11ed-a2b2-52b6cb0f4fb4,081aca6a-736e-11ed-a2b2-52b6cb0f4fb4,44,0.232880,5.901294,51.818197
9713,081698aa-736e-11ed-a2b2-52b6cb0f4fb4,081dd7d2-736e-11ed-a2b2-52b6cb0f4fb4,12,0.116489,10.457400,160.609298
...,...,...,...,...,...,...
995848,08122ed2-736e-11ed-a2b2-52b6cb0f4fb4,0929cdac-736e-11ed-a2b2-52b6cb0f4fb4,7,0.745259,9.145260,39.981627
995877,08122ed2-736e-11ed-a2b2-52b6cb0f4fb4,0929cfaa-736e-11ed-a2b2-52b6cb0f4fb4,25,0.997529,11.372719,80.674182
997411,0818d246-736e-11ed-a2b2-52b6cb0f4fb4,092a3a44-736e-11ed-a2b2-52b6cb0f4fb4,16,0.634799,18.979769,117.145706
997438,081698aa-736e-11ed-a2b2-52b6cb0f4fb4,092a3c24-736e-11ed-a2b2-52b6cb0f4fb4,15,0.787894,3.545313,213.897576
999105,0818d246-736e-11ed-a2b2-52b6cb0f4fb4,092aaf2e-736e-11ed-a2b2-52b6cb0f4fb4,34,0.330377,2.032947,0.592850

In [12]:
%%time

df.ps[ [ ('user',test_user_list),'or',[ ('user',test_user),'and',('category',2) ] ] ]

CPU times: user 2.26 ms, sys: 314 Âµs, total: 2.57 ms
Wall time: 2.55 ms

,user,event,category,a,b,c
900096,0818d246-736e-11ed-a2b2-52b6cb0f4fb4,090fd500-736e-11ed-a2b2-52b6cb0f4fb4,6,0.901381,20.894344,280.320217
300033,0818d246-736e-11ed-a2b2-52b6cb0f4fb4,086ce8e0-736e-11ed-a2b2-52b6cb0f4fb4,40,0.435608,8.941277,207.276589
568322,0818d246-736e-11ed-a2b2-52b6cb0f4fb4,08b5c470-736e-11ed-a2b2-52b6cb0f4fb4,31,0.084674,15.698218,145.005630
668680,08168b4e-736e-11ed-a2b2-52b6cb0f4fb4,08d0ffa6-736e-11ed-a2b2-52b6cb0f4fb4,19,0.421169,24.891166,86.844976
351240,0818d246-736e-11ed-a2b2-52b6cb0f4fb4,087ad040-736e-11ed-a2b2-52b6cb0f4fb4,3,0.827687,20.758733,47.340137
...,...,...,...,...,...,...
756728,08138002-736e-11ed-a2b2-52b6cb0f4fb4,08e8e24c-736e-11ed-a2b2-52b6cb0f4fb4,19,0.531301,0.996329,280.137201
314361,08122ed2-736e-11ed-a2b2-52b6cb0f4fb4,0870ca6e-736e-11ed-a2b2-52b6cb0f4fb4,24,0.036928,11.788005,153.009248
986106,08138002-736e-11ed-a2b2-52b6cb0f4fb4,09272746-736e-11ed-a2b2-52b6cb0f4fb4,6,0.953198,8.951610,64.748616
104438,08138002-736e-11ed-a2b2-52b6cb0f4fb4,0837ebb8-736e-11ed-a2b2-52b6cb0f4fb4,33,0.142473,19.294945,38.086656
816126,08138002-736e-11ed-a2b2-52b6cb0f4fb4,08f90fc8-736e-11ed-a2b2-52b6cb0f4fb4,2,0.412114,18.585074,92.746801

## Search with Mathematical Operators (Coming Soon)